#include <jni.h>
#include <string>
#include <cinttypes>
#include <android/log.h>
#include <kb.h>
#include <testdata.h>

#define LOGI(...) \
  ((void)__android_log_print(ANDROID_LOG_INFO, "knowledgepack-wrapper::", __VA_ARGS__))
extern "C"
JNIEXPORT void JNICALL
Java_com_sensiml_knowledgepackrunner_MainActivity_initSensiMLKnowledgePackModels(JNIEnv *env,
                                                                                 jclass clazz) {
    kb_model_init();
    LOGI("KB MODEL INIT");
}

extern "C"
JNIEXPORT jint JNICALL
Java_com_sensiml_knowledgepackrunner_MainActivity_runSensiMLKnowledgePackModel(JNIEnv *env,
                                                                               jobject thiz,
                                                                               jshortArray data,
                                                                               jint data_length) {
//This function is auto-generated by SensiML servers.
return -1;
}